#!/usr/bin/env bash
# Install nginx web server and start the service.
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo "Hello World!" > /var/www/html/index.nginx-debian.html



sudo service nginx restart

echo -e "\nCompleted. \n"
