#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.


# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Configure Nginx redirection
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/new-page;
    }
}' > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
