#!/usr/bin/env bash

# Install nginx web server
apt-get update -y
apt-get install nginx -y

# Ensure nginx is listening on port 80
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
kill -HUP $(cat /var/run/nginx.pid)

# Create index.html with redirect message
echo -e "<html><head><title>Redirecting...</title><meta http-equiv='refresh' content='0; URL=https://www.youtube.com/watch?v=QH2-TGUlwu4'></head><body><p>Redirecting to <a href='https://www.youtube.com/watch?v=QH2-TGUlwu4'>https://www.youtube.com/watch?v=QH2-TGUlwu4</a></p></body></html>" > /usr/share/nginx/html/redirect_me/index.html

# Configure nginx to redirect /redirect_me
echo -e "server {\n\tlisten 80;\n\tserver_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n}" > /etc/nginx/sites-available/redirect_me
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart nginx to apply changes
kill -HUP $(cat /var/run/nginx.pid)
