#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page 


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\        error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart

echo -e "\nCompleted.\n"
