#!/usr/bin/env bash

# Install nginx web server
apt-get update -y
apt-get install nginx -y

# Ensure nginx is listening on port 80
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
kill -HUP $(cat /var/run/nginx.pid)

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure nginx to use custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/custom_404

ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart nginx to apply changes
kill -HUP $(cat /var/run/nginx.pid)
