#!/usr/bin/env bash
# This  to configure web-02 to be identical to web-01

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set custom HTTP response header in Nginx configuration
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header X-Served-By $HOSTNAME;

    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx
