#!/bin/bash
# Bash manages manage_my_process

SCRIPT_PATH="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

start() {
    $SCRIPT_PATH &
    echo "$!" > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat "$PID_FILE")"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

if [ "$#" -eq 1 ]; then
    case "$1" in
        start)
            start
            ;;
        stop)
            stop
            ;;
        restart)
            restart
            ;;
        *)
            echo "Usage: $0 {start|stop|restart}"
            ;;
    esac
else
    echo "Usage: $0 {start|stop|restart}"
fi
