#!/bin/bash
# Bash manages manage_my_process

SCRIPT_PATH="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

if [ "$#" -eq 1 ]; then
    if [[ "$1" == "start" ]]; then
        
        $SCRIPT_PATH &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process started"
    elif [[ "$1" == "stop" ]]; then
      
        if test -f "$PID_FILE"; then
            kill "$(cat "$PID_FILE")"
        fi
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    elif [[ "$1" == "restart" ]]; then
   
        if test -f "$PID_FILE"; then
            kill "$(cat "$PID_FILE")"
        fi
        $SCRIPT_PATH &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process restarted"
    else
        echo "Usage: $0 {start|stop|restart}"
    fi
else
    echo "Usage: $0 {start|stop|restart}"
fi
