#!/usr/bin/env bash
# This Bash script that gives you information about the school file.


x="school"

if [ -e "$x" ]; then
    echo "school file exists"
    
    if [ -s "$x" ]; then
        echo "school file is not empty"
     
        if [ -f "$x" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
