#!/usr/bin/env bash
# Access the Docker container
# Start the Docker container with port mapping
docker run -p 8080:80 -d -it holbertonschool/265-0
container_id=$(docker ps -q)
docker exec -it "$container_id" /bin/bash
service apache2 status
cat /var/log/apache2/error.log
vi /etc/apache2/sites-available/000-default.conf

# Restart Apach
service apache2 restart

exit
curl 0:8080
