#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client
Host myserver
    HostName 172654-web-01
	User ubuntu
	IdentityFile ~/.ssh/school
	PreferredAuthentications publickey
	PasswordAuthentication no
